### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by leopoldomt** [lhaisrs/soar#2]
Seria interessante ter uma funcionalidade de adicionar um link web pra gerar um áudio, para escutar uma notícia, por exemplo. Algo na linha do que apps como Pocket (https://getpocket.com) ou Outline (https://outline.com) fazem, só que eles se concentram apenas em extrair o texto da matéria. 

A splash screen vai ser apresentada de 2 a 3 *minutos* ou *segundos*?

Link do proto acho que expirou, tem como gerar um pdf? 

@lhaisrs

**Comment by lhaisrs** [comment]
Feito!
